apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Netflix-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anuragingole17/DevSecOps-NetflixProject.git    # Replace it with your forked repo
    targetRevision: main
    path: Kubernetes
  destination:
    server: https://kubernetes.default.svc  # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
