name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4
      
      - name: Setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - run: npm install
      - run: npm test || echo "Tests failed but pipeline continues"

  sonar-test:
    name: Sonar-scanning
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=Netflix-github
            -Dsonar.projectName=Netflix-github
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  trivy-fs-scan:
    name: Trivy File Scan
    runs-on: ubuntu-latest
    needs: sonar-test
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 0
          format: table

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: trivy-fs-scan
    steps:
      - uses: actions/checkout@v4

      - name: Add commit-tag
        run: echo "IMAGE_TAG={GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/netflix:${IMAGE_TAG}.

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/netflix:${IMAGE_TAG}

          # ✅ Update deployment.yaml (GitOps)
      - name: Update image in deployment.yaml
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/netflix:${IMAGE_TAG}|" Kubernetes/deployment.yaml

      # ✅ Commit & push updated manifest
      - name: Commit and push deployment manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Kubernetes/deployment.yaml
          git commit -m "Update image to ${IMAGE_TAG}"
          git push


  trivy-image-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/netflix:${IMAGE_TAG}
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table

  
